@extends('layout.monster')
@section('content')

<div class="ktto-policy w3-animate-opacity">
    <h2>UNIVERSITY OF THE CORDILLERAS <br>  
        KNOWLEDGE AND TECHNOLOGY TRANSFER POLICY</h2>

    <div class="ktto-row">
        <div class="ktto-container">
            <h3>SECTION 6</h3>
            <h4 style="text-align: center">THE UC KNOWLEDGE AND TECHNOLOGY TRANSFER OFFICE <br>(UC-KTTO)</h4>
            
            <p>
        The UC-KTTO, under the Vice President for Academics and Research, shall be responsible for the implementation of the IP and the Tech Transfer Policies of the university. It shall be headed by a Director.
    </p>
    <p>
        The UC-KTTO assists the employees, students, partners, and external clients in commercializing their technology. In doing so, the KTTO strives to contribute to the public good, further economic development in the region, and enhance the research and development reputation of the university.
    </p>
    <ul>
        <li>
            <p><b><span>6.1</span> VISION</b></p>
            <p>The UC-KTTO envisions to be the leading advocate of knowledge and technology transfer services and IP management of researches and project outputs that aim to solve social and community problems in the country. </p>
        </li>
        <li>
            <p><b><span>6.2</span> MISSION AND OBJECTIVES</b></p>
            <p>The UC-KTTO aims to:</p>
            <ol type="a">
                <li>
                    Discover new knowledge and encourage the disclosure of research discoveries and inventions made by employees, students, and partners of the University.
                </li>
                <li>
                    Evaluate potential technology for appropriate intellectual property protection of employees, students, and partners of the University.
                </li>
                <li>
                    Assist in the licensing and protecting inventions and technology through Intellectual Property Rights.
                </li>
                <li>
                    Create commercialization strategies that will facilitate and encourage the transfer of technology.
                </li>
                <li>
                    Commercialize University research discoveries and inventions through tech transfer or creation of spin-off companies/start-up businesses.
                </li>
            </ol>
        </li>
        <li>
            <p><b><span>6.3</span> FUNCTIONS</b></p>
            <p>The UC-KTTO shall have the following functions:</p>
            <ol type="a">
                <li>
                    <p>To facilitate the efficient transfer of knowledge and technology from the University to the private sector in support of the public interest</p>
                </li>
                <li>
                    <p>To provide oversight supervision, guidance, and capacity-building on the IP office of UC, including but not limited to, IP audit, preparation, filing, and prosecution of applications for legal protection; and in handling technology transfer agreements;</p>
                </li>
                <li>
                    <p>To lead the UC in contested proceedings affecting IPR of other agencies in coordination with their respective legal counsels;</p>
                </li>
                <li>
                    <p>To lead in the preparation, filing, and prosecution of IP applications and registrations; </p>
                </li>
                <li>
                    <p>To lead UC in negotiating technology transfer arrangements such as but not limited to licensing agreements;</p>
                </li>
                <li>
                    <p>To collect royalties in coordination with UC finance office resulting from technology transfer arrangements and to manage and disburse the same in accordance with these guidelines;</p>
                </li>
                <li>
                    <p>To conduct capacity building in the technical know-how of technology transfer; and</p>
                </li>
                <li>
                    <p>To perform other functions to accomplish the purpose and objectives of the UC KTTO.</p>
                </li>
            </ol>
            <!--copied -->
            <p>To ensure that the UC Research and Innovation Office projects of the university will produce the intellectual properties of desired novelty, non-obviousness, and usefulness, the UC KTTO shall:</p>
            <ol type="a">
                <li>
                    <p>Determine the intellectual properties to be generated by the researchers from their proposed researches through a tagging mechanism. The data to be generated in the tagging shall be used by UC KTTO in auditing IPs generated by the researchers.</p>
                </li>
                <li>
                    <p>Ensure the novelty of the researches to be conducted by the researchers through prior art search, especially those researches that will bear method/process, products such as machine, microorganism, etc. In the absence of novelty, the UC KTTO shall recommend approaches to make the research novel.</p>
                </li>
                <li>
                    <p>Conduct plagiarism checking to the research proposals and terminal report in collaboration with Research Services Office, following separate guidelines for this purpose.</p>
                </li>
                <li>
                    <p>Perform a triage to the disclosed IPs, such as validations, to determine the existence, commercial value, and prioritization of the IPs to be protected.</p>
                </li>
                <li>
                    <p>Ensure the protection of the IPs generated from the researches and those assigned to the university, especially those that are commercially viable. Researchers that generate IPs from researches funded by the university and government agencies are required to disclose the IPs to UC KTTO.</p>
                </li>
            </ol>
        </li>
    </ul>
            <div class="ktto-buttom">
                <div class="ktto-buttom-column">
                    <a href="/ktto-section5">
                    <i class="fa fa-caret-left"></i> PREVIOUS</a>
                </div>
                <div style="text-align: center" class="ktto-buttom-column">
                    <a href="/ktto-policy-tb-content">TABLE OF CONTENTS</a>
                </div>
                <div style="text-align: right" class="ktto-buttom-column">
                    <a href="/ktto-section7">
                    NEXT <i class="fa fa-caret-right"></i></a>
                </div>
            </div>
            
        </div>
    </div>
</div>
@stop