@extends('layout.monster')
@section('content')

<div class="ktto-policy w3-animate-opacity">
    <h2>UNIVERSITY OF THE CORDILLERAS <br>  
        KNOWLEDGE AND TECHNOLOGY TRANSFER POLICY</h2>

    <div class="ktto-row">
        <div class="ktto-container">
            <h3>SECTION 10</h3>
            <h4 style="text-align: center">COMMERCIALIZATION</h4>
            
            <p>
                It is the objective of THE UC-KTTO to diligently pursue the best opportunities to transfer Intellectual Property consistent with the missions of the University and for the public benefit. In consultation with inventors, authors or creators, except as provided herein, UC-KTTO shall recommend to the consultants and examiners the actions to be taken concerning the route of commercializing or transferring a particular Intellectual Property, as well as the selection and use of outside resources, including outside legal counsel, to assist in commercialization.
            </p>
            <p>
                The UC-KTTO, generally, shall have authority for those agreements concerning the Tech Transfer of all University-owned intellectual property such as patent rights, computer software, and other copyrightable materials (such as electronic materials, written materials, and data) with any associated service agreements, and tangible materials.
            </p>
            <p>
                Responsibility for patent administration, including the retention of patent counsel, is shared by UC KTTO and the Office of the Vice President for Research and Innovation. Students, employees, researchers, and inventors who wish to commercialize their innovation shall adhere to the technology commercialization process at UC KTTO. (See commercialization Guidelines)
            </p>
            <ul>
                <li>
                    <p><b><span>10.1</span> Disbursement of Commercialization Benefits</b></p>
                    <p>
                        The University encourages the researchers and innovators by rewarding the creators of intellectual property with a share in the net commercialization revenue.
                    </p>
                    <p>
                        Net revenue is defined as the gross consideration (including all royalties, fees, and other benefits) received from the commercialization of the Intellectual Property less all expenses incurred in the commercialization of the Intellectual Property. Expenses shall include the following which will be deducted from the gross revenue:
                    </p>
                    <ol type="a">
                        <li>
                            all patent filing and legal fees;
                        </li>
                        <li>
                            marketing and licensing costs;
                        </li>
                        <li>
                            administrative expenses;
                        </li>
                        <li>
                            fixed overhead costs; and
                        </li>
                        <li>
                            any other expenses necessarily incurred for patenting and commercializing the Intellectual Property.
                        </li>
                    </ol>
                    <p>
                        Revenues generated by the licensing of University Intellectual Property provide a strong incentive for employees, students, and partners for participation in technology licensing and support further investment in research and technology transfer. The University shall share revenues received from commercialization efforts with all involved University inventors or authors, except as may otherwise be provided.
                    </p>
                    <p>
                        This Policy does not apply to funds received as gifts or for sponsored research. Amounts from third parties for or related to research, service, sponsorship, and/or philanthropy are under no circumstances included within the scope of “revenues,” even if they are mentioned in the course of negotiating and drafting related tech transfer or research agreements.
                    </p>
                    <p>
                        The University shall share with the inventor(s) or creator(s) of the Intellectual Property any revenue received by the University, in the following ratio:
                    </p>
                    <ul>
                        <li>
                            <p><span><b>*</b></span> 60% creator/s <br> -1 author 100% <br> -2 authors (main author 60%, co-author 40%) <br> -3 or more authors (main 40%, 60% among the rest)</p>
                        </li>
                        <li>
                            <span><b>*</b></span> 15% R&I, KTTO
                        </li>
                        <li>
                            <span><b>*</b></span> 10% UC
                        </li>
                        <li>
                            <span><b>*</b></span> 15% Mother Unit
                        </li>
                    </ul>
                    <p>
                        UC KTTO shall set and administer rules for determining the inventor (s) or creator (s) share of revenues within the parameters outlined in this Policy. This Policy, including the revenue sharing provisions, is subject to change with respect to both current and previous employees, students, and partners.
                    </p>
                    <p>
                        UC KTTO shall set and administer rules for cases where inventor (s) or creator (s):
                    </p>
                    <ol type="a">
                        <li>
                            changes department;
                        </li>
                        <li>
                            is affiliated with a university, institute or center;
                        </li>
                        <li>
                            does not have a department or school/college affiliation; or 
                        </li>
                        <li>
                            when other unusual circumstances apply.
                        </li>
                    </ol>
                    <p>
                        Although the University units described above shall have discretion for distributing the revenue they receive, generally, it is expected that revenues will be used for research and educational purposes or investment in further commercialization activities, such as in the laboratories of Inventors.
                    </p>
                    <p>
                        The Vice President for Academics and Research shall have the authority to resolve any unusual circumstances and may make exceptions to the distribution rules after consulting the affected parties.
                    </p>
                </li>
            </ul>
            <div class="ktto-buttom">
                <div class="ktto-buttom-column">
                    <a href="/ktto-section9">
                    <i class="fa fa-caret-left"></i> PREVIOUS</a>
                </div>
                <div style="text-align: center" class="ktto-buttom-column">
                    <a href="/ktto-policy-tb-content">TABLE OF CONTENTS</a>
                </div>
                <div style="text-align: right" class="ktto-buttom-column">
                    <a href="/ktto-section11">
                    NEXT <i class="fa fa-caret-right"></i></a>
                </div>
            </div>
            
        </div>
    </div>
</div>
@stop